INSERT INTO TAMANHOS(PESO_MARMITA, PRECO, INATIVO )
VALUES(12,2.50,0);

INSERT INTO TAMANHOS(PESO_MARMITA, PRECO, INATIVO )
VALUES(14,2.50,0);

INSERT INTO TAMANHOS(PESO_MARMITA, PRECO, INATIVO )
VALUES(15,2.50,0);

INSERT INTO TAMANHOS(PESO_MARMITA, PRECO,INATIVO )
VALUES(11,2.50,1);

INSERT INTO TAMANHOS(PESO_MARMITA, PRECO, INATIVO )
VALUES(5,2.50,1);


INSERT INTO TAMANHOS(PESO_MARMITA,PRECO, INATIVO )
VALUES(18,2.50,1);

INSERT INTO TAMANHOS(PESO_MARMITA,PRECO, INATIVO )
VALUES(19,2.50,0);
