INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('GORDUDA', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('PROTEINA', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('FIBRA', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('CARBOIDRATO', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('PROTEINA', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('CARBOIDRATO', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('CARBOIDRATO', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('PROTEINA', 0);
