INSERT INTO TAMANHOS(PESO_MARMITA, PRECO, INATIVO )
VALUES(500,6,0);

INSERT INTO TAMANHOS(PESO_MARMITA, PRECO, INATIVO )
VALUES(700,8,0);

INSERT INTO TAMANHOS(PESO_MARMITA, PRECO, INATIVO )
VALUES(1000,10,0);

INSERT INTO TAMANHOS(PESO_MARMITA, PRECO, INATIVO )
VALUES(1200,12,0);

INSERT INTO TAMANHOS(PESO_MARMITA, PRECO, INATIVO )
VALUES(1500,15,0);









