INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES( 'Ovo', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Carne de Frango', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Carne de Gado', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Arroz', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Feijão', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Água', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Farinha', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Milho', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Fubá', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Macarrão', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Carne Moída', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Farofa', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Molho', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Totame', 0);

INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('Pimenta', 0);


