INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('Gordura', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('Proteína', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('Fibra', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('Carboidrato', 0);

