INSERT INTO COMIDA_INGREDIENTES ( ID_COMIDA , ID_INGREDIENTES)
VALUES(1 ,2);

INSERT INTO COMIDA_INGREDIENTES ( ID_COMIDA , ID_INGREDIENTES)
VALUES(2 ,3);

INSERT INTO COMIDA_INGREDIENTES ( ID_COMIDA , ID_INGREDIENTES)
VALUES(3 ,4);

INSERT INTO COMIDA_INGREDIENTES ( ID_COMIDA , ID_INGREDIENTES)
VALUES(4 ,1);

INSERT INTO COMIDA_INGREDIENTES ( ID_COMIDA , ID_INGREDIENTES)
VALUES(5 ,6);

INSERT INTO COMIDA_INGREDIENTES ( ID_COMIDA , ID_INGREDIENTES)
VALUES(6 ,7);

INSERT INTO COMIDA_INGREDIENTES ( ID_COMIDA , ID_INGREDIENTES)
VALUES(7 ,8);

INSERT INTO COMIDA_INGREDIENTES ( ID_COMIDA , ID_INGREDIENTES)
VALUES(8 ,5);
