INSERT INTO CARDAPIO(CARDAPIO,DIA_SEMANA, INATIVO )
VALUES("PRATO DO DIA",'SEGUNDA',0);

INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES("FRITAS",'SEGUNDA',0);

INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES("BEBIDAS",'TERCA',0);

INSERT INTO CARDAPIO(CARDAPIO,DIA_SEMANA, INATIVO )
VALUES("ADICIONAIS",'QUARTA',0);

INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES("SEI LA",'QUINTA',0);

INSERT INTO CARDAPIO(CARDAPIO,DIA_SEMANA, INATIVO )
VALUES("OI GALERINHA",'SEXTA',0);
