INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('Macarrão', 0);

INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('Arroz', 0);

INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('Feijão', 0);

INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('Polenta', 0);

INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('Carne De Gado', 0);

INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('Carne De Frango', 0);

INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('Farofa', 0);

INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('Molho de Carne', 0);
