INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES("Feijoada",'SEGUNDA',0);

INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES("Moqueca Capixaba",'TERCA',0);

INSERT INTO CARDAPIO(CARDAPIO,DIA_SEMANA, INATIVO )
VALUES("Carne de sol",'QUARTA',0);

INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES("Acarajé",'QUINTA',0);

INSERT INTO CARDAPIO(CARDAPIO,DIA_SEMANA, INATIVO )
VALUES("Pato no Tucupi",'SEXTA',0);
