INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES('Feijoada','SEGUNDA',0);

INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES('Macarronada','TERCA',0);

INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES('Especial da Casa','QUARTA',0);

INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES('Assado de Frango','QUINTA',0);

INSERT INTO CARDAPIO(CARDAPIO, DIA_SEMANA,INATIVO )
VALUES('Lasanha','SEXTA',0);
