INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(1, 4);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(2, 4);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(3, 2);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(4, 4);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(5, 2);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(6, 2);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(7, 4);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(8, 2);
