CREATE TABLE FAVORITO(
ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_CLIENTE INTEGER NOT NULL,
ID_COMIDA INTEGER NOT NULL,
CONSTRAINT FK_FAVORITO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID),
CONSTRAINT FK_FAVORITO_COMIDA FOREIGN KEY (ID_COMIDA) REFERENCES COMIDA(ID)
);
