SELECT NOME as nome, pt.QUANTIDADE as quantidade , t.PRECO as preco, P.VALOR_TOTAL as valorTotal FROM  PEDIDO P INNER JOIN CLIENTES AS C
ON P.ID_CLIENTE = C.ID INNER JOIN PEDIDO_TAMANHO pt LEFT JOIN PEDIDO AS PI ON pt.ID_PEDIDO =
PI.ID INNER JOIN TAMANHOS AS t ON t.ID = pt.ID_TAMANHO
